apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  type: ClusterIP
  selector:
    app: hello
  ports:
  - name: http
    port: 80        # service (virtual) port
    targetPort: 80  # containerPort on the Pods